name: Create Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false
                    
      - name: Run setup
        run: bash setup.sh
          
      - name: Run tests
        run: bash tests/run_tests.sh

      - name: Run build
        run: bash build.sh ${{ github.ref_name }} ${{ github.sha }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/nshptt_*
          body_path: RELEASEINFO.md

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build
          retention-days: 1