name: NSHPTT Go Source Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  framelix-tests:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Display Go version
        run: go version
          
      - name: Run setup
        run: bash setup.sh
          
      - name: Run build
        run: bash build.sh
          
      - name: Run tests
        run: bash tests/run_tests.sh

      - name: Upload results after tests
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./nshptt/results
          retention-days: 5